<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$themeDirectory = $objectManager->get('\Magento\Framework\View\Asset\Repository');

$currentStoreCode = $storeManager->getStore()->getCode();
$imagePath = $themeDirectory->getUrlWithParams('Magento_Theme::img/metalopro-white.svg', ['_secure' => $storeManager->getStore()->isCurrentlySecure()]);

if ($currentStoreCode == 'steelbro_cz') {
    $imagePath = $themeDirectory->getUrlWithParams('Magento_Theme::img/metaloprocz-white.svg', ['_secure' => $storeManager->getStore()->isCurrentlySecure()]);
}
if ($currentStoreCode == 'default') {
	$imagePath = $themeDirectory->getUrlWithParams('Magento_Theme::img/logo-mobile.svg', ['_secure' => $storeManager->getStore()->isCurrentlySecure()]);
}

?>

<a class="ammenu-logo mobile" href="/" title="MetaloPro" aria-label="store logo">
    <img src="<?php echo $imagePath; ?>" alt="MetaloProLogo">
</a>
