<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$themeDirectory = $objectManager->get('\Magento\Framework\View\Asset\Repository');
$imagePath = $themeDirectory->getUrlWithParams('Magento_Checkout::img/TrustedShop.svg', ['_secure' => $storeManager->getStore()->isCurrentlySecure()]);
?>
<div class="trusted-shop-badge"><img src="<?php $imagePath; ?>"></div>