<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div
    class="relative inline-block"
    x-data="{ open: false }"
    @keyup.escape="open = false"
    @click.outside="open = false"
>
    <button
        type="button"
        id="customer-menu"
        class="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-gray-100 text-slate-700 hover:bg-gray-200 transition-colors"
        @click="open = !open"
        :aria-expanded="open ? 'true' : 'false'"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
        aria-haspopup="true"
    >
        <?= $heroicons->userHtml('h-5 w-5', 20, 20, ['aria-hidden' => 'true']); ?>
    </button>
    <nav
        class="absolute right-0 z-20 w-48 py-2 mt-2 overflow-auto origin-top-right rounded-xl shadow-xl border border-gray-200 bg-white"
        x-cloak
        x-show="open"
        aria-labelledby="customer-menu"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <?= $block->getChildHtml('header.customer.logged.in.links') ?>
        <?php else: ?>
            <?= $block->getChildHtml('header.customer.logged.out.links') ?>
        <?php endif; ?>
    </nav>
</div>
