<?php
/** @var $block \Magento\Catalog\Block\Product\View */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$assetRepo = $objectManager->get(\Magento\Framework\View\Asset\Repository::class);
$productRepository = $objectManager->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
$configurableType = $objectManager->get(\Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable::class);
$registry = $objectManager->get(\Magento\Framework\Registry::class);

$_product = $registry->registry('current_product');
if (!$_product) {
    echo '<!-- Product not found -->';
    return;
}
$buttonTitle = __('Prejsť na konfiguráciu');

$imagePath = $assetRepo->getUrlWithParams(
    'Magento_Checkout::img/cart.svg',
    ['_secure' => $storeManager->getStore()->isCurrentlySecure()]
);

$imageCheckPath = $assetRepo->getUrlWithParams(
    'Magento_Checkout::img/check.svg',
    ['_secure' => $storeManager->getStore()->isCurrentlySecure()]
);

$block_payment = $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)
    ->setBlockId('payment-icon');

$iconUrl = $assetRepo->getUrlWithParams(
        'MetaloPro_GateCategoryControl::images/gear-white.svg',
        ['_secure' => $storeManager->getStore()->isCurrentlySecure()]
    );

$dostupnost = $_product->getAttributeText('dostupnost');

// Získaj configurable parent
$parentIds = $configurableType->getParentIdsByChild($_product->getId());
$configurableProduct = !empty($parentIds) ? $productRepository->getById($parentIds[0]) : null;
$configurableUrl = $configurableProduct ? $configurableProduct->getProductUrl() : '#';
?>

<?php if ($configurableProduct) : ?>
    <?php if (!empty($dostupnost)) : ?>
        <div class="stock available">
            <div class="delivery-time">
                <span class="dostupnost"><img src="<?= $imageCheckPath ?>" alt="Check"> <?= $dostupnost ?></span>
            </div>
        </div>
    <?php endif; ?>
    <div class="to-cart-group">
        <div class="box-tocart" style="margin-bottom: 22px;">
            <div class="fieldset">

                <div class="actions">
                    <a href="<?= $configurableUrl ?>"
                       title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                       class="action primary tocart" id="product-configurable-link">
                        <img src="<?= $iconUrl ?>" alt="Cart" />
                        <span><?= $block->escapeHtml($buttonTitle) ?></span>
                    </a>

                    

                    <?= $block->getChildHtml('', true) ?>
                </div>

            </div>
        </div>

        <?php if ($block_payment) : ?>
            <?= $block_payment->toHtml() ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
