<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$width = (int)$block->getWidth();
$paddingBottom = $block->getRatio() * 100;
?>

<?php 
/** @var $block \Magento\Catalog\Block\Product\Image */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Catalog\Model\ProductRepository $productRepository */
$productRepository = $objectManager->get(\Magento\Catalog\Model\ProductRepository::class);
$currentProduct = $productRepository->getById($block->getProductId());
$imageFile = $currentProduct->getCustomAttribute('hover');
$imageValue = ($imageFile) ? $imageFile->getValue() : null;

// Later on...
if ($imageValue) {
    $resizedImageUrl = $this->helper('Magento\Catalog\Helper\Image')
        ->constrainOnly(TRUE)
           ->keepAspectRatio(TRUE)
           ->keepFrame(FALSE)
           ->init($currentProduct, 'hover_product_list')
           ->setImageFile($imageValue)
           ->resize(350, 350)  // Pridajte túto riadku na nastavenie rozmerov
           ->getUrl();
}
?>
<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?> <?php if ($imageFile) { ?>
    hovered <?php } ?>" >
    <span class="product-image-wrapper">
        <?php if ($imageFile) { ?>
            <?php if (strpos($resizedImageUrl, 'placeholder') == false) { ?>
        <img class="products-image-hover" data-src="<?= $resizedImageUrl ?>"
            src="<?= $resizedImageUrl ?>"
            loading="lazy"
            width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
            height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
            alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"/>
        <?php }} ?>
        <img class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtml($value) ?>"
            <?php endforeach; ?>
            src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
            loading="lazy"
            width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
            height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
            title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
            alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"/></span>
</span>
<?php
$styles = <<<STYLE
.product-image-container-{$block->getProductId()} {
    width: {$width}px;
}
.product-image-container-{$block->getProductId()} span.product-image-wrapper {
    padding-bottom: {$paddingBottom}%;
}
STYLE;
//In case a script was using "style" attributes of these elements
$script = <<<SCRIPT
prodImageContainers = document.querySelectorAll(".product-image-container-{$block->getProductId()}");
for (var i = 0; i < prodImageContainers.length; i++) {
    prodImageContainers[i].style.width = "{$width}px";
}
prodImageContainersWrappers = document.querySelectorAll(
    ".product-image-container-{$block->getProductId()}  span.product-image-wrapper"
);
for (var i = 0; i < prodImageContainersWrappers.length; i++) {
    prodImageContainersWrappers[i].style.paddingBottom = "{$paddingBottom}%";
}
SCRIPT;

?>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styles, false) ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false) ?>
