<div class="custom-production-widget">
	<div class="widget-content">
		<img src="<?= $block->getViewFileUrl('Magento_Theme::images/widget/metalio-user-big.png') ?>" alt="Metalio person" class="widget-image">
		<div class="widget-text">
			<h3>Potrebujete vypáliť niečo na mieru?</h3>
			<p>Či už ide o presné <b>vypaľovanie z plechu</b>, <b>rezanie profilov alebo rúrok</b>, s našimi modernými technológiami dokážeme zrealizovať aj tie najnáročnejšie požiadavky.</p>
		</div>
		<div class="actions">
		<a href="/vyroba-na-mieru" class="button secondary modal-opener">Kontaktovať</a>
	</div>
	</div>
	
	
</div>