<?php if ($block->getGeneralSettings('active_category')) { 
$popupId = uniqid('popup-modal-contact-');
$clickId = uniqid('click-me-');
?>
<li class="item product product-item contact_form_category">
<div class="contact_us_bar_widget">
	<img class="contact-us-image" src="<?= $block->getAvatar(); ?>" alt="avatar">
	<div class="contact-us-text">
        <div class="text-top">
		  <p class="main_text"><b><?= $block->getBlockCategoryTitle(); ?></b></p>
		  <p class="long_text"><?= $block->getBlockCategoryMessage(); ?></p>
        </div>
        <p class="draw_timing">
            <img alt="time-img" src="<?php echo $this->getViewFileUrl('BigConnect_ContactForms::images/time.svg'); ?>">
            <b><?= $block->getBlockCategoryTime(); ?></b>
        </p>
		<div class="cta-block">
			<div class="actions">
				<button href="javascript:void(0)" id="<?php echo $clickId ?>" class="action primary">
					<span><?= $block->escapeHtml(__('Write us a message')) ?></span>
				</button>
			</div>
		</div>
	</div>
</div>
<div id="<?php echo $popupId ?>" style="display: none;">
    <?php include("forms/form_product.phtml"); ?>
</div>
</li>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass: 'bigconnect_form',
                title: "<?php echo __('Contact Form')?>",
                buttons: false
            };
 
            var popup = modal(options, $('#<?php echo $popupId ?>'));
			$(document.body).on('click', '#<?php echo $clickId ?>', function (e) {
				e.stopImmediatePropagation();
				$("#<?php echo $popupId ?>").modal("openModal");
			});
        }
    );
</script>
<?php } ?>