<?php if ($block->shouldRenderSubcategoryListing()): ?>
	<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$assetRepo = $objectManager->get(\Magento\Framework\View\Asset\Repository::class);
$imageCheckPath = $assetRepo->getUrlWithParams(
    'MetaloPro_GateCategoryControl::images/info.svg',
    ['_secure' => $storeManager->getStore()->isCurrentlySecure()]
);
?>
<div class="product-info-note">
  <img src="<?= $imageCheckPath ?>" alt="info"> <span>Vieme vyrobiť aj atypické rozmery a prispôsobiť detaily podľa vašich predstáv.</span>
</div>
<?php endif; ?>