<div class="cart-benefit-group d-flex">
    <div class="single benefit d-flex">
        <div class="benefit-icon">
            <img src="<?= $block->getViewFileUrl('Magento_Checkout::images/secure-card.svg'); ?>" alt="Check Icon" width="48" height="48">
        </div>
        <div class="benefit-text-group d-flex">
            <div class="benefit-headline"><?= __('Secure Purchase') ?></div>
            <span class="u-txt-dark"><?= __('Payments secured with 3D secure') ?></span>
        </div>
    </div>

    <div class="single benefit d-flex">
        <div class="benefit-icon">
            <img src="<?= $block->getViewFileUrl('Magento_Checkout::images/europe.svg'); ?>" alt="Europe Icon" width="48" height="48">
        </div>
        <div class="benefit-text-group d-flex">
            <div class="benefit-headline"><?= __('Made in the EU') ?></div>
            <span class="u-txt-dark"><?= __('Buy directly from a European manufacturer') ?></span>
        </div>
    </div>

    <div class="single benefit d-flex">
        <div class="benefit-icon">
            <img src="<?= $block->getViewFileUrl('Magento_Checkout::images/quality.svg'); ?>" alt="Quality Icon" width="48" height="48">
        </div>
        <div class="benefit-text-group d-flex">
            <div class="benefit-headline"><?= __('High Quality') ?></div>
            <span class="u-txt-dark"><?= __('Durable and reliable products') ?></span>
        </div>
    </div>

    <div class="single benefit d-flex">
        <div class="benefit-icon">
            <img src="<?= $block->getViewFileUrl('Magento_Checkout::images/recomend.svg'); ?>" alt="Recommend Icon" width="48" height="48">
        </div>
        <div class="benefit-text-group d-flex">
            <div class="benefit-headline"><?= __('Recommended by Customers') ?></div>
            <span class="u-txt-dark"><?= __('99% of satisfied customers who return to us') ?></span>
        </div>
    </div>

    <div class="single benefit d-flex">
        <div class="benefit-icon">
            <img src="<?= $block->getViewFileUrl('Magento_Checkout::images/support.svg'); ?>" alt="Support Icon" width="48" height="48">
        </div>
        <div class="benefit-text-group d-flex">
            <div class="benefit-headline"><?= __('Customer Support') ?></div>
            <span class="u-txt-dark"><?= __('Friendly online support 24/7') ?></span>
        </div>
    </div>
</div>
