<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storePhone = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('general/store_information/phone');
$storeHours = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('general/store_information/hours');
$storeEmail = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('trans_email/ident_general/email');
?>
<div class="contact_left">
	<div class="contact-links-wrap">
		<div class="h4"><?= $block->escapeHtml(__('Customer support')) ?></div>
		<ul class="contact-links">
			<li class="contact-phone-badge">
				<div class="icon-contact">
					<img src="/pub/media/wysiwyg/steelbro/contact/phone-white.svg">
				</div>
				<a href="tel:<?= $storePhone; ?>" title="<?= $storePhone; ?>"><?= $storePhone; ?></a>
			</li>
			<li class="contact-email-badge">
				<div class="icon-contact">
					<img src="/pub/media/wysiwyg/steelbro/contact/mail-white.svg">
				</div>
				<a href="mailto:<?= $storeEmail; ?>"><?= $storeEmail; ?></a>
				
			</li>
			<li class="store-open-badge">
				<div class="icon-contact">
					<img src="/pub/media/wysiwyg/steelbro/contact/time-white.svg">
				</div>
				<span><?= $storeHours; ?></span>

				
			</li>
		</ul>
	</div>
	<div class="contact-links-wrap invoice">
		<div class="h4"><?= $block->escapeHtml(__('Billing information')) ?></div>
		<ul class="contact-links">
			<li>BigConnect s.r.o.</li>
			<li>Harhaj 1</li>
			<li>08645 Harhaj</li>
			<li>IČO: 53342992</li>
			<li>DIČ: 2121344533</li>
			<li>IČ DPH: SK2121344533</li>
		</ul>
	</div>
	
</div>