<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
  <?php 
  $dostupnost = $_product->getAttributeText('dostupnost');
  ?>
<div class="powder-colors-icon d-flex gap-2">
  <img src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/powder-colors.png'); ?>" alt="Powder Colors">
  <div class="powder-text d-flex gap-2">
      <span class="powder-color-text"><?= $block->escapeHtml(__('Práškové farby')); ?></span>
     <!-- <a href="#" class="powder-color-info modal-powder-opener">Viac informácií</a> -->
  </div>
</div>
  <?php if ($block->displayProductStockStatus()) :?>
      <?php if ($_product->isAvailable()) :?>
        <?php if (!empty($dostupnost)) { ?>
          <div class="stock-available">
              <div class="delivery-time d-flex align-items-center gap-2">
                  <div class="delivery-icon d-flex align-items-center me-2">
              <svg role="presentation" focusable="false" stroke-width="2" width="18" height="18" class="icon icon-success" style="--icon-height: 18px" viewBox="0 0 18 18">
                      <path d="M0 9C0 4.02944 4.02944 0 9 0C13.9706 0 18 4.02944 18 9C18 13.9706 13.9706 18 9 18C4.02944 18 0 13.9706 0 9Z" fill="#31a33b"></path>
                      <path d="M5 8.8L7.62937 11.6L13 6" stroke="#ffffff" fill="none"></path>
                    </svg>
          </div>
              <span class="dostupnost stock in_stock available"><?php echo $dostupnost; ?></span>
            </div>
          </div>
      <?php } ?>
      <?php else :?>
          <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
              <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
          </div>
      <?php endif; ?>
  <?php endif; ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php
echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')
    ->setTemplate('Magento_Catalog::product/view/payments-icon.phtml')
    ->toHtml();
?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
