<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    
        <ul class="custom_attributes">
            <?php foreach ($_additional as $_data) :?>
                <li class="d-flex items-center">
                    <div class="attribute-name"><?= $block->escapeHtml($_data['label']) ?></div>
                    <div class="atribute-value"><?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></div>
                </li>
            <?php endforeach; ?>
        </ul>
  
<?php endif;?>
