<div class="add-to-cart-payment d-flex gap-1 justify-center">
    <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/paypal.png'); ?>" alt="paypal">
    <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/mastercard.png'); ?>" alt="mastercard">
    <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/visa.png'); ?>" alt="visa">
    <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/googlepay.png'); ?>" alt="googlepay">
    <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/klarna.png'); ?>" alt="applepay" style="background: #f9b3c7;">
</div>
