<div style="display:none" data-mage-init='{
        "Magento_Ui/js/modal/modal": {
            "trigger": ".modal-powder-opener"
        }
    }' class="powder-colors-block">
	<h3>Naše práškové farby</h3>
	<div class="powder-color-box d-flex">
		<div class="color-info">
			<img src="/pub/media/wysiwyg/powder-colors/black.jpg">
			<div class="color-name">
			<h4>Čierna</h4>
			<span>Ral9005</span>
			</div>
		</div>
		<div class="color-gallery d-flex">
			
		</div>
	</div>
	<div class="powder-color-box d-flex">
		<div class="color-info">
			<img src="/pub/media/wysiwyg/powder-colors/antracit.jpg">
			<div class="color-name">
			<h4>Antracit</h4>
			<span>Ral9005</span>
			</div>
		</div>
		<div class="color-gallery d-flex">
			
		</div>
	</div>
	<div class="powder-color-box d-flex">
		<div class="color-info">
			<img src="/pub/media/wysiwyg/powder-colors/white.jpg">
			<div class="color-name">
			<h4>Biela</h4>
			<span>Ral9005</span>
			</div>
		</div>
		<div class="color-gallery d-flex">
			
		</div>
	</div>

</div>