<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>
 
<div class="flex flex-col lg:flex-row-reverse lg:items-start gap-8 ">
    <div class="d-flex wrap lg:order-1 order-2 ">
    <?= $block->getChildHtml('trustbar') ?>
    <div class="lg:w-80 2xl:w-96 lg:sticky lg:top-2 bg-gray-100 rounded-2xl p-6 text-center">

        <div class="flex flex-col mb-2 pb-3">
            <h2 class="text-2xl text-gray-900 title-font font-bold text-left">
                <?= $escaper->escapeHtml(__('Summary')) ?>
            </h2>
        </div>
        
        <?= $block->getChildHtml('cart.summary') ?>


    </div>
    </div>
    <div class="lg:flex-1 lg:order-2 order-1">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
  
    </div>
</div>
