<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<div class="grid gap-6 lg:gap-10 grid-cols-1 lg:grid-cols-2">
    <div class="area-main space-y-6">
        <?= $block->getChildHtml('column.main') ?>
        <?= $block->getChildHtml('column.center') ?>
    </div>


    <div class="area-right checkout-summary space-y-6">
        <?= $block->getChildHtml('column.right') ?>
        <?= $block->getChildHtml('hyva.checkout.navigation') ?>
    </div>
</div>

<style type="text/css">
    @media (min-width: 1024px) {
      #maincontent {
        position: relative;
        margin: 0px !important;
        padding-top: 2rem;
        padding-bottom: 2rem;
      }

      #maincontent::after {
        content: "";
        position: absolute;
        top: 0;
        right: 0;
        width: 50%;   /* polovica */
        height: 100%;
        background-color: #f5f5f5; /* Tailwind bg-gray-100 */
        z-index: -1; /* aby to neprekrylo obsah */
      }
    }
</style>
