<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<span class="footer-headline"><?= $block->escapeHtml(__('Sign Up for Our Newsletter')) ?></span>
<div class="block-newsletter mb-4">

    <p><?= $block->escapeHtml(__('Receive notifications of new products and changes.')) ?></p>
    <div class="newsletter-group">
        <form class="form subscribe d-flex flex-column gap-3"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="subscribe-input-group d-flex mb-3">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                   
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
            </div>
            <div class="inputs-newsletter">
                         <div class="field choice newsletter">
                          <input type="checkbox" name="is_subscribed2" title="Prihlásiť sa do newslettra" id="is_subscribed2" class="checkbox" data-validate="{required:true, 'validate-one-required-by-name':true}">
                          <label for="is_subscribed2" class="label"><span><?php echo __('I agree to processing of my personal data.') ?></span></label>
                        </div>
                    </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
