<?php if ($block->getCookiesEnable()) { ?> 
<!-- Cookie Consent by https://www.FreePrivacyPolicy.com -->
<script type="text/javascript" src="//www.freeprivacypolicy.com/public/cookie-consent/4.0.0/cookie-consent.js" charset="UTF-8"></script>
<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
	"notice_banner_type":"simple",
	"consent_type":"express",
	"palette":"light",
	"language":"<?= $block->getCountry(); ?>",
	"page_load_consent_levels":["strictly-necessary"],
	"notice_banner_reject_button_hide":false,
	"preferences_center_close_button_hide":false,
	"page_refresh_confirmation_buttons":false,
	"website_name":"<?= $block->getName(); ?>",
	"website_privacy_policy_url":"<?= $block->getPrivacyPolicyUrl(); ?>"});
});
</script>
<!-- End Cookie Consent -->
<?php } ?>

	




