<div class="c-header__exit">
	<a href="/" class="c-link" title="<?= $block->escapeHtml(__('Exit the shopping process')) ?>">
		<span class="cxs-end"><?= $block->escapeHtml(__('Exit the shopping process')) ?></span>
		<svg width="10" height="10" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
			<path d="M1 11L11 1M1 1L11 11" stroke="#1A1A1A" stroke-width="2" stroke-linecap="round"/>
		</svg>
	</a>
</div>